#!/bin/csh

foreach machine ( worker1 worker2 worker3 worker4 worker5 worker6 worker7 worker8 worker9 worker10 worker11 worker12 worker13 worker14 worker15 worker16 worker17 worker18 worker19  )

	echo $machine

	scp -rp /home/cc/testIO/readMPI  ${machine}:/home/cc/testIO/readMPI
end
